juice-file ::= 
    | top-level-declaration*
    | EOF 

top-level-declaration ::= 
    | export-declaration
    | expression

export-declaration ::=
    | 'export' declaration

declaration ::=
    | function-declaration
    | variable-declaration

function-declaration ::= 'let' identifier '=' function-arguments (':' type) '->' function-body
function-arguments ::= '(' ((typed-identifier) (',' typed-identifier)* ))? ')'
function-body ::= block

variable-declaration ::= 
    | 'let' identifier '=' expression

block ::=  '{' statements* '}'

statements ::= 
    | variable-declaration
    | expression

expression ::= 
    | equality

equality ::= comparison ( ( "!=" | "==" ) comparison )*
comparison ::= addition ( ( ">" | ">=" | "<" | "<=" ) addition )*
addition ::= multiplication ( ( "-" | "+" ) multiplication )*
multiplication ::= unary ( ( "/" | "*" ) unary )*
unary ::= 
    | ( "!" | "-" ) unary 
    | expression
    | identifier
    | LITERAL

typed-identifier ::= identifier ':' type
type ::= 
    | BOOLEAN_TYPE
    | INT_TYPE
    | FLOAT_TYPE

identifier ::= IDENTIFIER