name: Juiced CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  typecheck_test_lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Node.js 12 environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 12.x
      - name: Checkout repository code
      - uses: actions/checkout@v2
      - name: Install depenencies
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Test
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
      - name: Lint
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
      - name: Typecheck
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: typecheck
